// Code generated by protoc-gen-go.
// source: URProtocol.proto
// DO NOT EDIT!

package URWWPacketProtocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type URProtocol struct {
	Uri       URPacketType `protobuf:"varint,1,opt,name=uri,enum=URWWPacketProtocol.URPacketType" json:"uri,omitempty"`
	Header    *PHeader     `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	LoginReq  *URLoginReq  `protobuf:"bytes,3,opt,name=loginReq" json:"loginReq,omitempty"`
	LoginRes  *URLoginRes  `protobuf:"bytes,4,opt,name=loginRes" json:"loginRes,omitempty"`
	LogoutReq *URLogoutReq `protobuf:"bytes,5,opt,name=logoutReq" json:"logoutReq,omitempty"`
	LogoutRes *URLogoutRes `protobuf:"bytes,6,opt,name=logoutRes" json:"logoutRes,omitempty"`
}

func (m *URProtocol) Reset()                    { *m = URProtocol{} }
func (m *URProtocol) String() string            { return proto.CompactTextString(m) }
func (*URProtocol) ProtoMessage()               {}
func (*URProtocol) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *URProtocol) GetUri() URPacketType {
	if m != nil {
		return m.Uri
	}
	return URPacketType_kUriInvalid
}

func (m *URProtocol) GetHeader() *PHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *URProtocol) GetLoginReq() *URLoginReq {
	if m != nil {
		return m.LoginReq
	}
	return nil
}

func (m *URProtocol) GetLoginRes() *URLoginRes {
	if m != nil {
		return m.LoginRes
	}
	return nil
}

func (m *URProtocol) GetLogoutReq() *URLogoutReq {
	if m != nil {
		return m.LogoutReq
	}
	return nil
}

func (m *URProtocol) GetLogoutRes() *URLogoutRes {
	if m != nil {
		return m.LogoutRes
	}
	return nil
}

type URLoginReq struct {
	Passport string `protobuf:"bytes,1,opt,name=passport" json:"passport,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *URLoginReq) Reset()                    { *m = URLoginReq{} }
func (m *URLoginReq) String() string            { return proto.CompactTextString(m) }
func (*URLoginReq) ProtoMessage()               {}
func (*URLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *URLoginReq) GetPassport() string {
	if m != nil {
		return m.Passport
	}
	return ""
}

func (m *URLoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type URLoginRes struct {
}

func (m *URLoginRes) Reset()                    { *m = URLoginRes{} }
func (m *URLoginRes) String() string            { return proto.CompactTextString(m) }
func (*URLoginRes) ProtoMessage()               {}
func (*URLoginRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type URLogoutReq struct {
	Passport string `protobuf:"bytes,1,opt,name=passport" json:"passport,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *URLogoutReq) Reset()                    { *m = URLogoutReq{} }
func (m *URLogoutReq) String() string            { return proto.CompactTextString(m) }
func (*URLogoutReq) ProtoMessage()               {}
func (*URLogoutReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *URLogoutReq) GetPassport() string {
	if m != nil {
		return m.Passport
	}
	return ""
}

func (m *URLogoutReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type URLogoutRes struct {
}

func (m *URLogoutRes) Reset()                    { *m = URLogoutRes{} }
func (m *URLogoutRes) String() string            { return proto.CompactTextString(m) }
func (*URLogoutRes) ProtoMessage()               {}
func (*URLogoutRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func init() {
	proto.RegisterType((*URProtocol)(nil), "URWWPacketProtocol.URProtocol")
	proto.RegisterType((*URLoginReq)(nil), "URWWPacketProtocol.URLoginReq")
	proto.RegisterType((*URLoginRes)(nil), "URWWPacketProtocol.URLoginRes")
	proto.RegisterType((*URLogoutReq)(nil), "URWWPacketProtocol.URLogoutReq")
	proto.RegisterType((*URLogoutRes)(nil), "URWWPacketProtocol.URLogoutRes")
}

func init() { proto.RegisterFile("URProtocol.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x08, 0x0d, 0x0a, 0x28,
	0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2b, 0x00, 0x31, 0x84, 0x84, 0x42, 0x83, 0xc2, 0xc3,
	0x03, 0x12, 0x93, 0xb3, 0x53, 0x4b, 0x60, 0x32, 0x52, 0x42, 0xa1, 0x41, 0x10, 0x91, 0x90, 0xca,
	0x82, 0x54, 0x88, 0x3a, 0xa5, 0xd7, 0x4c, 0x5c, 0x5c, 0x08, 0xcd, 0x42, 0x46, 0x5c, 0xcc, 0xa5,
	0x45, 0x99, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0x0a, 0x7a, 0x98, 0x86, 0xe8, 0x21, 0x9b,
	0x11, 0x04, 0x52, 0x2c, 0x64, 0xcc, 0xc5, 0x96, 0x91, 0x9a, 0x98, 0x92, 0x5a, 0x24, 0xc1, 0xa4,
	0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0x8d, 0x4d, 0x5b, 0x80, 0x07, 0x58, 0x49, 0x10, 0x54, 0xa9, 0x90,
	0x15, 0x17, 0x47, 0x4e, 0x7e, 0x7a, 0x66, 0x5e, 0x50, 0x6a, 0xa1, 0x04, 0x33, 0x58, 0x9b, 0x1c,
	0x76, 0xdb, 0x7c, 0xa0, 0xaa, 0x82, 0xe0, 0xea, 0x91, 0xf4, 0x16, 0x4b, 0xb0, 0x10, 0xa1, 0xb7,
	0x18, 0xae, 0xb7, 0x58, 0xc8, 0x96, 0x8b, 0x33, 0x27, 0x3f, 0x3d, 0xbf, 0xb4, 0x04, 0x64, 0x31,
	0x2b, 0x58, 0xb3, 0x3c, 0x4e, 0xcd, 0x10, 0x65, 0x41, 0x08, 0x1d, 0xc8, 0xda, 0x8b, 0x25, 0xd8,
	0x88, 0xd1, 0x5e, 0x8c, 0xd0, 0x5e, 0xac, 0xe4, 0x02, 0x0a, 0x6c, 0x98, 0x8f, 0x84, 0xa4, 0xb8,
	0x38, 0x0a, 0x12, 0x8b, 0x8b, 0x0b, 0xf2, 0x8b, 0x4a, 0xc0, 0x21, 0xce, 0x19, 0x04, 0xe7, 0xc3,
	0xe4, 0xca, 0xf3, 0x8b, 0x52, 0xc0, 0xc1, 0x0a, 0x95, 0x03, 0xf1, 0x95, 0x78, 0x90, 0x4c, 0x29,
	0x56, 0x72, 0xe5, 0xe2, 0x46, 0x72, 0x2c, 0xd9, 0x86, 0xf2, 0x22, 0x1b, 0x53, 0x9c, 0xc4, 0x06,
	0x4e, 0x1e, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0xff, 0xb1, 0x76, 0x5a, 0x02, 0x00,
	0x00,
}
